// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Sample
{
	public partial class GlassButton : UIButton
	{
		public GlassButton (IntPtr handle) : base (handle)
		{
		}
	}
}
